server:
  port: 8083
spring:
  application:
    name: authentication-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

jwt:
  secret: jhfiuwefiifeiofijo5367566B59703373sdfgfddf367639792F423F4528482B4D6251655468576D5A71347437